
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"EPIC-CHAT-ON-OFF-MAIN","number":43,"title":"Epic chat on off main","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/43"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-AnnouncementsF2","number":42,"title":"Kole Announcements F2 - Index and Create page","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/42"},{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"HY-EPIC-CHAT-ON-OFF-2","number":41,"title":"Hy epic chat on off 2","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/41"},{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"HL-chat-button-display","number":40,"title":"show/hide chat button","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/40"},{"author":{"id":"U_kgDOBcwKVw","is_bot":false,"login":"JustinZhang809","name":""},"headRefName":"JustinZ-CommonsFutureDateBug","number":39,"title":"JustinZ - Commons Future Date Bug","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/39"},{"author":{"id":"U_kgDOBXi6pA","is_bot":false,"login":"anguyen412","name":""},"headRefName":"AN-AnnouncementsController","number":38,"title":"AN - B2 added controllers and tests for Announcements","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/38"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-AnnouncementsF1","number":35,"title":"Kole - Announcements F1","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/35"}]
