
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"HL-FixNegativeBuy","number":15,"title":"Hl fix negative buy","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/15"},{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"HY-OurTablePagination","number":14,"title":"hy - adding pagination to OurTable component","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/14"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-LeaderboardBack","number":13,"title":"Moved leaderboard back button to right side of page","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/13"}]
