
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBXi6pA","is_bot":false,"login":"anguyen412","name":""},"headRefName":"AN-EntityRepoAnnouncements","number":33,"title":"AN - added entity/repository for announcements","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/33"},{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"HY-EPIC-CHAT-ON-OFF-1-3","number":31,"title":"HY - EPIC-CHAT-ON-OFF-1-3","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/31"},{"author":{"id":"U_kgDOBXj98A","is_bot":false,"login":"rmarangoly","name":""},"headRefName":"Rohan-NegativeCows","number":24,"title":"Rohan - fixed selling negative cows bug and tests","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/24"},{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"HY-OurTablePagination","number":14,"title":"HY - adding pagination to OurTable component","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/14"}]
