
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"ktkikuta-patch-1","number":45,"title":"Update README.md","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/45"},{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"EPIC-CHAT-ON-OFF-MAIN","number":43,"title":"Merging CHAT-ON-OFF epic issue into main","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/43"}]
