
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBXi6pA","is_bot":false,"login":"anguyen412","name":""},"headRefName":"AN-AnnouncementsController","number":38,"title":"AN - added controllers and tests for Announcements","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/38"},{"author":{"id":"U_kgDOBclbpw","is_bot":false,"login":"hongye-liang","name":""},"headRefName":"HL-EPIC-CHAT-effective-backend","number":37,"title":"Hl epic chat effective backend","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/37"},{"author":{"id":"U_kgDOBXj98A","is_bot":false,"login":"rmarangoly","name":""},"headRefName":"EPIC-CHAT-COMMONS-TABLE","number":36,"title":"RM- Chat Commons Table","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/36"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-AnnouncementsF1","number":35,"title":"Kole - Announcements F1","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/35"},{"author":{"id":"U_kgDOBXj98A","is_bot":false,"login":"rmarangoly","name":""},"headRefName":"EPIC-CHAT-COMMONS-FORM","number":34,"title":"RM - added showChat checkbox to frontend and tests","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/34"}]
